/* eslint-disable */
export const STORYBOOK_STORE: any = {
  user: {
    isLoggedIn: true,
    isInitiated: true,
    error: '',
    isLoading: false,
    isTokenRefreshing: false,
    authData: {
      _id: '66111016b60543776c5564dc',
      username: '6paTyxa_6e3_CkuJIJIyxu',
      email: 'testt@test.ru',
      avatar: 'https://i.ibb.co/6mFMhKT/default-avatar2.jpg',
      roles: [],
      awards: [],
      ra_rating: 1000,
      teams: [],
      sessions: [
        '66111024b60543776c5564f7',
        '66131a4b23622ed46a068fa5',
      ],
      balance: 0,
      isActivated: false,
      activationLink: '1fa9b747-6220-47b5-9814-125cb31ae01b',
      wn8: 3447,
      created_at: '2024-04-06T09:04:22.404Z',
      lestaData: {
        nickname: '6paTyxa_6e3_CkuJIJIyxu',
        access_token: '0a971973d21822962998267a392a3095ea27f8db',
        account_id: 82166719,
        expires_at: '2024-04-22T14:32:54.000Z',
      },
      clan: {
        name: 'OLRCY TEAM',
        tag: 'OLRCY',
        clan_id: 92496,
        role: 'executive_officer',
      },
      statistics: {
        battles: 32269,
        winRate: 71.28,
        avgDamage: 2532,
        wn8: 3447,
        wins: 23000,
        losses: 9098,
        draws: 171,
      },
      sessionStatistics: {
        battles: 0,
        winRate: 0,
        avgDamage: 0,
        wn8: 0,
        wins: 0,
        losses: 0,
        draws: 0,
      },
      bio: 'qwerty',
      vk: 'skillzor',
      discord: '282193117250060289',
    },
  },
  searchForm: {
    search: '',
    players: [],
    clans: [],
  },
  tournaments: {
    tournaments: [],
    ladders: [],
    finished: [],
    isLoading: false,
    error: '',
  },
  lesta: {
    isLoading: false,
    isNotFound: false,
    user: null,
    userTanks: null,
    clan: null,
    error: null,
  },
  lestaUserData: {
    isLoading: false,
    isNotFound: false,
    error: '',
    statistics: {
      battles: 32269,
      winRate: 71.28,
      avgDamage: 2532,
      wn8: 3447,
      wins: 23000,
      losses: 9098,
      draws: 171,
      last_battle_time: 1712446819,
    },
    personal: {
      _id: '66111016b60543776c5564dc',
      id: '66111016b60543776c5564dc',
      username: '6paTyxa_6e3_CkuJIJIyxu',
      email: 'testt@test.ru',
      avatar: 'https://i.ibb.co/6mFMhKT/default-avatar2.jpg',
      bio: 'qwerty',
      discord: '282193117250060289',
      vk: 'skillzor',
      created_at: '2024-04-06T09:04:22.404Z',
      roles: [],
      ra_rating: 1000,
      balance: 0,
      isActivated: false,
      sessions: [
        {
          id: '66111024b60543776c5564f7',
          session_date: '2024-04-06T09:04:37.012Z',
        },
        {
          id: '66131a4b23622ed46a068fa5',
          session_date: '2024-04-07T22:12:27.387Z',
        },
      ],
      lestaData: {
        nickname: '6paTyxa_6e3_CkuJIJIyxu',
        account_id: 82166719,
        expires_at: '2024-04-22T14:32:54.000Z',
        access_token: '0a971973d21822962998267a392a3095ea27f8db',
      },
    },
    private: {
      premium: 1763078329,
      gold: 24890,
      free_xp: 864701,
      credits: 27843322,
    },
    rating: {
      battles: 3817,
      winRate: 55.99,
      avgDamage: 2100,
      wn8: 0,
      wins: 2137,
      losses: 1668,
      draws: 12,
      last_battle_time: 1712446819,
    },
    ratingValues: {
      ratingValue: 3000,
      calibration_battles_left: 10,
    },
    clan: {
      name: 'OLRCY TEAM',
      tag: 'OLRCY',
      clan_id: 92496,
      role: 'executive_officer',
    },
  },
  lestaUserSession: {
    isLoading: false,
    isNotFound: false,
    error: '',
    data: {
      delta: {
        battles: 0,
        winRate: 0,
        avgDamage: 0,
        wn8: 0,
        wins: 0,
        losses: 0,
        draws: 0,
      },
      statistics: {
        battles: 0,
        winRate: 0,
        avgDamage: 0,
        wn8: 0,
        wins: 0,
        losses: 0,
        draws: 0,
        session_start_time: 1712527947,
      },
      tanks: [],
    },
  },
  teams: {
    myTeams: [],
    openedTeams: [],
    topTeams: [],
    isLoading: false,
    error: '',
  },
  userTanks: {
    isLoading: false,
    userTanks: [
      {
        tank_id: 14609,
        tankData: {
          _id: '660ffd41ebf7357c9936d575',
          tank_id: 14609,
          name: 'Leopard 1',
          type: 'mediumTank',
          tier: 10,
          nation: 'germany',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/Leopard1.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/Leopard1.png',
          description: null,
        },
        statistics: {
          battles: 2204,
          winRate: 68.33,
          avgDamage: 2858,
          wn8: 3556.58,
          wins: 1506,
          losses: 686,
          draws: 12,
          mark_of_mastery: 4,
          last_battle_time: 1712446819,
        },
      },
      {
        tank_id: 12049,
        tankData: {
          _id: '660ffd41ebf7357c9936d506',
          tank_id: 12049,
          name: 'Jagdpanzer E 100',
          type: 'AT-SPG',
          tier: 10,
          nation: 'germany',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/JagdPz_E100.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/JagdPz_E100.png',
          description: null,
        },
        statistics: {
          battles: 191,
          winRate: 68.59,
          avgDamage: 2619,
          wn8: 2451.46,
          wins: 131,
          losses: 59,
          draws: 1,
          mark_of_mastery: 4,
          last_battle_time: 1712443479,
        },
      },
      {
        tank_id: 13889,
        tankData: {
          _id: '660ffd41ebf7357c9936d557',
          tank_id: 13889,
          name: 'AMX 50 Foch (155)',
          type: 'AT-SPG',
          tier: 10,
          nation: 'france',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/AMX_50Fosh_155.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/AMX_50Fosh_155.png',
          description: null,
        },
        statistics: {
          battles: 123,
          winRate: 63.41,
          avgDamage: 2667,
          wn8: 2704.3,
          wins: 78,
          losses: 45,
          draws: 0,
          mark_of_mastery: 4,
          last_battle_time: 1712442421,
        },
      },
      {
        tank_id: 14113,
        tankData: {
          _id: '660ffd41ebf7357c9936d560',
          tank_id: 14113,
          name: 'M48 Patton',
          type: 'mediumTank',
          tier: 10,
          nation: 'usa',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/M48A1.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/M48A1.png',
          description: null,
        },
        statistics: {
          battles: 859,
          winRate: 68.22,
          avgDamage: 2878,
          wn8: 3597.49,
          wins: 586,
          losses: 270,
          draws: 3,
          mark_of_mastery: 4,
          last_battle_time: 1712440700,
        },
      },
      {
        tank_id: 16897,
        tankData: {
          _id: '660ffd41ebf7357c9936d5d2',
          tank_id: 16897,
          name: 'Об. 140',
          type: 'mediumTank',
          tier: 10,
          nation: 'ussr',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/Object_140.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/Object_140.png',
          description: null,
        },
        statistics: {
          battles: 1041,
          winRate: 71.37,
          avgDamage: 2866,
          wn8: 3605.15,
          wins: 743,
          losses: 289,
          draws: 9,
          mark_of_mastery: 4,
          last_battle_time: 1712439647,
        },
      },
      {
        tank_id: 385,
        tankData: {
          _id: '660ffd41ebf7357c9936d13a',
          tank_id: 385,
          name: 'Progetto M40 mod. 65',
          type: 'mediumTank',
          tier: 10,
          nation: 'european',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/It08_Progetto_M40_mod65.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/It08_Progetto_M40_mod65.png',
          description: 'In 1969, the Italian military delegation visited Germany to discuss the purchase of Leopard tanks. However, not all members of the delegation agreed with the acquisition of foreign vehicles. The Italian military experts and engineers specified the main requirements for the future tank: the slope angle of armor plates, the cast turret and gun mantlet, as well as the powerful engine from Mitsubishi that allowed production of a small, light, maneuverable, but perfectly-armored vehicle. The British and Soviet design plans collected by SIFAR-SID were taken into account. Development of the project was discontinued at the drafting and modelling stage.',
        },
        statistics: {
          battles: 197,
          winRate: 68.02,
          avgDamage: 2905,
          wn8: 3216.69,
          wins: 134,
          losses: 63,
          draws: 0,
          mark_of_mastery: 4,
          last_battle_time: 1712439466,
        },
      },
      {
        tank_id: 3649,
        tankData: {
          _id: '660ffd41ebf7357c9936d251',
          tank_id: 3649,
          name: 'Bat.-Châtillon 25 t',
          type: 'lightTank',
          tier: 10,
          nation: 'france',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/Bat_Chatillon25t.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/Bat_Chatillon25t.png',
          description: null,
        },
        statistics: {
          battles: 1434,
          winRate: 71.13,
          avgDamage: 2717,
          wn8: 3423.24,
          wins: 1020,
          losses: 403,
          draws: 11,
          mark_of_mastery: 4,
          last_battle_time: 1712438544,
        },
      },
      {
        tank_id: 15697,
        tankData: {
          _id: '660ffd41ebf7357c9936d59f',
          tank_id: 15697,
          name: 'Chieftain Mk. 6',
          type: 'heavyTank',
          tier: 10,
          nation: 'uk',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/GB84_Chieftain_Mk6.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/GB84_Chieftain_Mk6.png',
          description: 'The tank entered service in May 1963 and was produced until 1985. A total of 2,265 vehicles were manufactured.',
        },
        statistics: {
          battles: 1646,
          winRate: 73.82,
          avgDamage: 2907,
          wn8: 2999.4,
          wins: 1215,
          losses: 426,
          draws: 5,
          mark_of_mastery: 4,
          last_battle_time: 1712437180,
        },
      },
      {
        tank_id: 21841,
        tankData: {
          _id: '660ffd41ebf7357c9936d6b0',
          tank_id: 21841,
          name: 'Caliban',
          type: 'heavyTank',
          tier: 8,
          nation: 'uk',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/GB112_Caliban.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/GB112_Caliban.png',
          description: 'The Caliban is a project of the Royal Military College developed in 1962. The vehicle certainly was not pretty, but it was supposed to feature excellent movement characteristics, reliable frontal armor, and a powerful gun. The project turned out to be too complicated and expensive, and its numerous innovations did not guarantee any advantages over the vehicles in production and development. Work was discontinued at the drafting stage, and no prototypes were built.',
        },
        statistics: {
          battles: 5,
          winRate: 60,
          avgDamage: 2136,
          wn8: 0,
          wins: 3,
          losses: 2,
          draws: 0,
          mark_of_mastery: 1,
          last_battle_time: 1712091692,
        },
      },
      {
        tank_id: 16705,
        tankData: {
          _id: '660ffd41ebf7357c9936d5cf',
          tank_id: 16705,
          name: 'AMX M4 mle. 49',
          type: 'heavyTank',
          tier: 8,
          nation: 'france',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/F74_AMX_M4_1949.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/F74_AMX_M4_1949.png',
          description: null,
        },
        statistics: {
          battles: 61,
          winRate: 73.77,
          avgDamage: 2356,
          wn8: 0,
          wins: 45,
          losses: 16,
          draws: 0,
          mark_of_mastery: 3,
          last_battle_time: 1712091443,
        },
      },
      {
        tank_id: 2945,
        tankData: {
          _id: '660ffd41ebf7357c9936d21e',
          tank_id: 2945,
          name: 'Progetto M35 mod. 46',
          type: 'mediumTank',
          tier: 8,
          nation: 'european',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/It13_Progetto_M35_mod_46.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/It13_Progetto_M35_mod_46.png',
          description: 'Conceptualization of a draft design developed at the request of General Francesco Rossi who believed that only light vehicles weighing up to 35 tons would be effective in a new war. Such an innovative design was not approved; development was discontinued when Italy joined the Standard Tank project.',
        },
        statistics: {
          battles: 538,
          winRate: 76.77,
          avgDamage: 2224,
          wn8: 3144.42,
          wins: 413,
          losses: 122,
          draws: 3,
          mark_of_mastery: 4,
          last_battle_time: 1712091188,
        },
      },
      {
        tank_id: 54289,
        tankData: {
          _id: '660ffd41ebf7357c9936d7ee',
          tank_id: 54289,
          name: 'Löwe',
          type: 'heavyTank',
          tier: 8,
          nation: 'germany',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/Lowe.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/Lowe.png',
          description: null,
        },
        statistics: {
          battles: 84,
          winRate: 78.57,
          avgDamage: 2303,
          wn8: 0,
          wins: 66,
          losses: 18,
          draws: 0,
          mark_of_mastery: 3,
          last_battle_time: 1712090637,
        },
      },
      {
        tank_id: 19985,
        tankData: {
          _id: '660ffd41ebf7357c9936d650',
          tank_id: 19985,
          name: 'Rheinmetall Skorpion G',
          type: 'AT-SPG',
          tier: 8,
          nation: 'germany',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/G114_Rheinmetall_Scorpion.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/G114_Rheinmetall_Scorpion.png',
          description: 'Development of the second series of self-propelled guns on the basis of the Panther tank was started by the Rheinmetall company in January 1943. The design plans for the 12,8 cm Skorpion were completed on April 2, 1943. Existed only in blueprints.',
        },
        statistics: {
          battles: 63,
          winRate: 71.43,
          avgDamage: 2251,
          wn8: 0,
          wins: 45,
          losses: 18,
          draws: 0,
          mark_of_mastery: 4,
          last_battle_time: 1712090281,
        },
      },
      {
        tank_id: 18769,
        tankData: {
          _id: '660ffd41ebf7357c9936d614',
          tank_id: 18769,
          name: 'Caernarvon Action X',
          type: 'heavyTank',
          tier: 8,
          nation: 'uk',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/GB93_Caernarvon_AX.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/GB93_Caernarvon_AX.png',
          description: 'A further development of the vehicles designed by the English Electric company under the "universal tank" concept (FV200). The project was discontinued in favor of the A41 tank (Centurion). No prototypes were built.',
        },
        statistics: {
          battles: 161,
          winRate: 77.02,
          avgDamage: 2315,
          wn8: 3116.26,
          wins: 124,
          losses: 36,
          draws: 1,
          mark_of_mastery: 3,
          last_battle_time: 1712089623,
        },
      },
      {
        tank_id: 20481,
        tankData: {
          _id: '660ffd41ebf7357c9936d665',
          tank_id: 20481,
          name: 'Об. 252У',
          type: 'heavyTank',
          tier: 8,
          nation: 'ussr',
          is_premium: true,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/R134_Object_252U.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/R134_Object_252U.png',
          description: 'A draft project, prepared during the development of the IS-6 heavy tank. The draft was completed by the end of 1944. Later, work on the IS-6 tank was stopped, and the development of the project was discontinued. The vehicle never entered service.',
        },
        statistics: {
          battles: 78,
          winRate: 66.67,
          avgDamage: 2347,
          wn8: 0,
          wins: 52,
          losses: 26,
          draws: 0,
          mark_of_mastery: 3,
          last_battle_time: 1711924137,
        },
      },
      {
        tank_id: 18977,
        tankData: {
          _id: '660ffd41ebf7357c9936d61d',
          tank_id: 18977,
          name: 'T95E6',
          type: 'heavyTank',
          tier: 10,
          nation: 'usa',
          is_premium: true,
          is_collectible: true,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/A95_T95E6.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/A95_T95E6.png',
          description: 'Some military analysts deemed the experimental tanks of the T95 series to be undergunned. In order to increase the tank\'s firepower, a new, heavier turret, designated T96, was to be mounted on the hull. This would allow replacement of the 105-mm gun with a 120-mm gun. However, development proved unsuccessful, and the project was canceled on July 7th, 1960. Only one dummy vehicle was built.',
        },
        statistics: {
          battles: 87,
          winRate: 78.16,
          avgDamage: 3156,
          wn8: 0,
          wins: 68,
          losses: 19,
          draws: 0,
          mark_of_mastery: 4,
          last_battle_time: 1711920216,
        },
      },
      {
        tank_id: 4481,
        tankData: {
          _id: '660ffd41ebf7357c9936d29c',
          tank_id: 4481,
          name: 'Kranvagn',
          type: 'heavyTank',
          tier: 10,
          nation: 'european',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/S16_Kranvagn.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/S16_Kranvagn.png',
          description: 'A project for a new vehicle for the Swedish army that started in 1949. For confidentiality purposes, the vehicle was given an unusual name, KRV, which stands for self-propelled crane (in Swedish). The project was based on the French AMX 50. A lightweight chassis was built and tested; in addition, a dummy with a turret was produced. A prototype was never built.',
        },
        statistics: {
          battles: 112,
          winRate: 58.93,
          avgDamage: 3228,
          wn8: 3251.52,
          wins: 66,
          losses: 45,
          draws: 1,
          mark_of_mastery: 4,
          last_battle_time: 1711859373,
        },
      },
      {
        tank_id: 20257,
        tankData: {
          _id: '660ffd41ebf7357c9936d65c',
          tank_id: 20257,
          name: 'XM551 Sheridan',
          type: 'lightTank',
          tier: 10,
          nation: 'usa',
          is_premium: false,
          is_collectible: false,
          image: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd/A116_XM551.png',
          image_preview: 'https://glossary-na-static.gcdn.co/icons/wotb/current/uploaded/vehicles/hd_thumbnail/A116_XM551.png',
          description: 'Work on the vehicle started under the AR/AAV project (Armored Reconnaissance/Airborne Assault Vehicle) in January 1959. In June 1962, the Cadillac Motor Car Division delivered the first vehicle prototype to the client. The first generation of vehicles included three prototypes. Work was continued, and the vehicle eventually saw service under the M551 Sheridan designation in 1966.',
        },
        statistics: {
          battles: 1392,
          winRate: 69.76,
          avgDamage: 3014,
          wn8: 3457.39,
          wins: 971,
          losses: 411,
          draws: 10,
          mark_of_mastery: 4,
          last_battle_time: 1711858540,
        },
      },
    ],
    error: null,
  },
};
